### ISSUE TITLE
Wrong result with readme example

### ISSUE THREAD

**Issue by sysescool** [dpuyda/scheduling#33]
```bash
cd $home
git clone https://github.com/dpuyda/scheduling.git
mkdir build
cd build
cmake ..
make

cd $home
mkdir scheduling_test && cd scheduling_test
cp ../scheduling/build/libscheduling.a ./
cp ../scheduling/include/scheduling.hpp ./
echo "g++ -std=c++20 -o main main.cpp -L./ -lscheduling" > build.sh
chmod a+x build.sh
vim main.cpp
```
copy below code to main.cpp, then run `cd $home/scheduling_test && ./build.sh`
```cpp
#include <iostream>
#include <vector>
#include "scheduling.hpp"

int main() {
  scheduling::ThreadPool thread_pool;
	
  std::cout << "hello, sleep" << std::endl;
  thread_pool.Submit([] {
    std::this_thread::sleep_for(std::chrono::seconds(1));
    std::cout << "Completed.\n";
  });
  std::cout << "hello, sleep finish" << std::endl;

  int a, b, c, d;
  std::vector<scheduling::Task> tasks;

  auto& get_a = tasks.emplace_back([&] {
    a = 1;
  });

  auto& get_b = tasks.emplace_back([&] {
    b = 2;
  });

  auto& get_c = tasks.emplace_back([&] {
    c = 3;
  });

  auto& get_d = tasks.emplace_back([&] {
    d = 4;
  });

  int sum_ab, sum_cd;

  auto& get_sum_ab = tasks.emplace_back([&] {
    sum_ab = a + b;
  });

  auto& get_sum_cd = tasks.emplace_back([&] {
    sum_cd = c + d;
  });

  int product;

  auto& get_product = tasks.emplace_back([&] {
    product = sum_ab * sum_cd;
  });
  // define task dependencies
  // get_sum_ab run after get_a and get_b
  get_sum_ab.Succeed(&get_a, &get_b);
  get_sum_cd.Succeed(&get_c, &get_d);
  get_product.Succeed(&get_sum_ab, &get_sum_cd);

  // scheduling::ThreadPool thread_pool;
  thread_pool.Submit(tasks);
  // block the currnet thread until all submitted tasks are completed.
  thread_pool.Wait();

  std::cout << "a:" << a << " b:" << b << " c:" << c << " d:" << d << std::endl;
  std::cout << "a + b = " << sum_ab << std::endl;
  std::cout << "c + d = " << sum_cd << std::endl;
  std::cout << "(a + b) * (c + d) = " << product << std::endl;
  return 0;
}
```
after build, run `./main`, get result:
```
hello, sleep
hello, sleep finish
Completed.
a:1 b:2 c:3 d:4
a + b = 0
c + d = 0
(a + b) * (c + d) = 0
```

**Comment by dpuyda** [comment]
Hi!
Thanks for reporting! Let me check and get back to you!

**Comment by dpuyda** [comment]
@sysescool, thanks again for your interest in the project! I think your issue might happen because you did not reserve enough space in `tasks`, and thus your references might be invalidated. In your case, it seems you need to reserve space for 7 tasks:
```cpp
  std::vector<scheduling::Task> tasks;
  tasks.reserve(7);
```
Please note that the README file warns the reader that the `Task` instances should not be destroyed or reallocated until their execution is completed by `ThreadPool`. For further reference, you can also check the [unit tests](https://github.com/dpuyda/scheduling/blob/main/tests/thread_pool_test.cpp#L95).

I would be grateful if you could check if the example works for you with this fix and let me know. I will make sure to update the README.md to highlight the importance of pre-allocating space!

**Comment by dpuyda** [comment]
@sysescool, I have updated README.md, please check https://github.com/dpuyda/scheduling/pull/34/files
Thank you very much for your comment, it has been very useful! Please let me know if the above fix works for you.

**Comment by sysescool** [comment]
it is fixed. thank you.

**Comment by dpuyda** [comment]
Thank you very much for the update, @sysescool! Alternatively, for example, you can use `std::list` or other containers which do not reallocate elements, or add tasks to an `std::vector` without calling `reserve` and then reference tasks by indices, but I personally would prefer `std::vector` and `reserve` when possible. Typically, we create class wrappers for our task graphs to wrap an `std::vector` of tasks and the shared state. I will add an example to demonstrate this when I have time.

I'm closing the issue according to your comment, thanks again for your time and for your interest in the project!
